---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Justin Neria.
--- DateTime: 1/26/2018 9:22 PM
---

require "gooi"

menuButton_xLocation = love.graphics.getWidth() / 2 - love.graphics.getWidth() / 10
menuButton_yLocation = love.graphics.getHeight() / 2 - love.graphics.getHeight() / 8
menuButton_yIncrement = love.graphics.getHeight() / 12
menuButtonHeight = love.graphics.getHeight() / 12
menuButtonWidth = love.graphics.getWidth() / 5

local function init()
    local startBtn = gooi.newButton({
        text = "Start",
        x = menuButton_xLocation,
        y = menuButton_yLocation,
        w = menuButtonWidth,
        h = menuButtonHeight,
        group = "main_menu"
    }):onRelease()

    local settingsBtn = gooi.newButton({
        text = "Settings",
        x = menuButton_xLocation,
        y = menuButton_yLocation + menuButton_yIncrement,
        w = menuButtonWidth,
        h = menuButtonHeight,
        group = "main_menu"
    }):onRelease(function()
        gooi.draw("settings")
    end)

    local exitBtn = gooi.newButton({
        text = "Quit",
        x = menuButton_xLocation,
        y = menuButton_yLocation + (menuButton_yIncrement * 2),
        w = menuButtonWidth,
        h = menuButtonHeight,
        group = "main_menu",
        icon = "imgs/exit.png"
    }):onRelease(function()
        gooi.confirm({
            text = "Are you sure?",
            ok = function()
                love.event.quit()
            end
        })
    end)
            :warning()

    local settingsPanel = gooi.newPanel({
        x  = 0,
        y = 0,
        w = 430,
        h = 150,
        layout = "grid 2x4"
    })

    settingsPanel:setColspan(1,1,2)
    settingsPanel:setColspan(3,1,2)
    settingsPanel:add(
        gooi.newLabel({text = "Text Speed"}),
        gooi.newSlider({value = .5}),
        gooi.newLabel({text = "1"}),
        gooi.newLabel({text = "Sound"}),
        gooi.newSlider({value = .5}),
        gooi.newLabel({text = "2"})
    )
end

